#::::::::::#
#::Server::#
#::::::::::#

# Hostname (Fully qualified domain name)
server.hostname = "mail.{{ brand.domain }}"

# Connections
server.max-connections = 1024
server.socket.backlog = 1024
server.socket.nodelay = true
server.socket.reuse-addr = true
server.socket.reuse-port = true

# Autoban
server.auto-ban.abuse.rate = "35/1d"
server.auto-ban.auth.rate = "20/1d"
server.auto-ban.loiter.rate = "150/1d"
server.auto-ban.scan.paths.00 = "*.php*"
server.auto-ban.scan.paths.01 = "*.cgi*"
server.auto-ban.scan.paths.02 = "*.asp*"
server.auto-ban.scan.paths.03 = "*/wp-*"
server.auto-ban.scan.paths.04 = "*/php*"
server.auto-ban.scan.paths.05 = "*/cgi-bin*"
server.auto-ban.scan.paths.06 = "*xmlrpc*"
server.auto-ban.scan.paths.07 = "*../*"
server.auto-ban.scan.paths.08 = "*/..*"
server.auto-ban.scan.paths.09 = "*joomla*"
server.auto-ban.scan.paths.10 = "*wordpress*"
server.auto-ban.scan.paths.11 = "*drupal*"
server.auto-ban.scan.rate = "20/1d"

#::::::::::::#
#::Webadmin::#
#::::::::::::#

# Auto update webadmin on startup
webadmin.auto-update = true

# Unpack location for webadmin
webadmin.path = "/opt/stalwart-mail/webadmin"

#:::::::::::::::::::#
#::Fallback::Admin::#
#:::::::::::::::::::#

authentication.fallback-admin.secret = "{{ stalwart.admin.pass }}"
authentication.fallback-admin.user = "{{ stalwart.admin.user }}"

#::::::::#
#::IMAP::#
#::::::::#

# Authentication
imap.auth.max-failures = 3
imap.auth.allow-plain-text = false

# Timeout
imap.timeout.authenticated = "30m"
imap.timeout.anonymous = "1m"
imap.timeout.idle = "30m"

# Rate Limits
imap.rate-limit.requests = "100/1m"
imap.rate-limit.concurrent = 4

#:::::::::::::::::::::#
#::Spam::&::Phishing::#
#:::::::::::::::::::::#

# Trusted domains
lookup.trusted-domains = [
    "{{ brand.domain }}",
    "mail.{{ brand.domain }}"
]

#::::::::::::::::::#
#::ACME::Provider::#
#::::::::::::::::::#

acme.letsencrypt.directory = "https://acme-v02.api.letsencrypt.org/directory"
acme.letsencrypt.challenge = "dns-01"
acme.letsencrypt.contact = "{{ system.email.admin }}"
acme.letsencrypt.domains = [
    "{{ brand.domain }}",
    "mail.{{ brand.domain }}"
]
acme.letsencrypt.default = true
acme.letsencrypt.provider = "cloudflare"
acme.letsencrypt.secret = "{{ cf.api_token }}"
acme.letsencrypt.renew-before = "30d"

#:::::::::::::#
#::Listeners::#
#:::::::::::::#

# HTTPS
server.listener.https.bind = "[::]:443"
server.listener.https.protocol = "http"
server.listener.https.tls.implicit = true

# HTTP (unencrypted - do not expose)
server.listener.http.bind = "[::]:8080"
server.listener.http.protocol = "http"

# IMAP (unencrypted)
server.listener.imap.protocol = "imap"
server.listener.imap.bind = "[::]:143"

# IMAP (over TLS)
server.listener.imaptls.protocol = "imap"
server.listener.imaptls.bind = "[::]:993"
server.listener.imaptls.tls.implicit = true

# SMTP (Submissions)
server.listener.smtp.bind = "[::]:25"
server.listener.smtp.protocol = "smtp"
server.listener.smtp.greeting = "Welcome to {{ brand.name }} Mail"

# SMTP (over StartTLS)
server.listener.submission.bind = "[::]:587"
server.listener.submission.protocol = "smtp"

# SMTP (over TLS)
server.listener.submissions.bind = "[::]:465"
server.listener.submissions.protocol = "smtp"
server.listener.submissions.tls.implicit = true

# POP3 (unencrypted)
server.listener.pop3.bind = "[::]:110"
server.listener.pop3.protocol = "pop3"

# POP3 (over TLS)
server.listener.pop3s.bind = "[::]:995"
server.listener.pop3s.protocol = "pop3"
server.listener.pop3s.tls.implicit = true

# JMAP (over TLS)
server.listener.jmap.bind = ["[::]:8080"]
server.listener.jmap.protocol = "http"
server.listener.jmap.tls.implicit = true

#:::::::::::#
#::Folders::#
#:::::::::::#

# Folders - Inbox
jmap.folders.inbox.name = "Inbox"
jmap.folders.inbox.create = true
jmap.folders.inbox.subscribe = true

# Folders - Sent
jmap.folders.sent.name = "Sent"
jmap.folders.sent.create = true
jmap.folders.sent.subscribe = true

# Folders - Junk
jmap.folders.junk.name = "Spam"
jmap.folders.junk.create = true
jmap.folders.junk.subscribe = true

# Folders - Drafts
jmap.folders.drafts.name = "Drafts"
jmap.folders.drafts.create = true
jmap.folders.drafts.subscribe = true

# Folders - Trash
jmap.folders.trash.name = "Trash"
jmap.folders.trash.create = true
jmap.folders.trash.subscribe = true

# Folders - Archive
jmap.folders.archive.name = "Archive"
jmap.folders.archive.create = true
jmap.folders.archive.subscribe = true

#:::::::::::::::::::::#
#::Storage::Settings::#
#:::::::::::::::::::::#

# The core storage unit where email metadata, folders, and various settings are stored. 
# Essentially, it contains all the data except for large binary objects (blobs).
storage.data = "stalwart-mail-db"

# This store is used for storing large binary objects such as 
# emails, sieve scripts, and other files.
storage.blob = "stalwart-mail-db"

# This store is dedicated to indexing for full-text search, 
# enhancing the speed and efficiency of text-based queries.
storage.fts = "stalwart-mail-db"

# A key-value storage used by different security, clustering and anti-spam components.
storage.lookup = "stalwart-mail-db"

# Used for authentication
# By default built-in rocksdb. This config directly specifies our own database.
storage.directory = "internal"

# Encryption
storage.encryption.enable = true
storage.encryption.append = true

#::::::::::::#
#::Database::#
#::::::::::::#

# Main Database
store.stalwart-mail-db.type = "mysql"
store.stalwart-mail-db.host = "{{ stalwart.db.host }}"
store.stalwart-mail-db.port = 3309
store.stalwart-mail-db.database = "{{ stalwart.db.name }}"
store.stalwart-mail-db.user = "{{ stalwart.db.user }}"
store.stalwart-mail-db.password = "{{ stalwart.db.pass }}"
store.stalwart-mail-db.compression = "lz4"
store.stalwart-mail-db.pool.max-connections = 10
store.stalwart-mail-db.pool.min-connections = 5
store.stalwart-mail-db.purge.frequency = "0 3 *"
store.stalwart-mail-db.read-from-replicas = true
store.stalwart-mail-db.timeout = "30s"
store.stalwart-mail-db.tls.allow-invalid-certs = false
store.stalwart-mail-db.tls.enable = false

#:::::::::::::::#
#::Directories::#
#:::::::::::::::#

# Default directory
directory.internal.store = "stalwart-mail-db"
directory.internal.type = "internal"

#:::::::::::::::::::::::::::#
#::TLS::Aggregate::Reports::#
#:::::::::::::::::::::::::::#

report.tls.aggregate.from-name = "'TLS Report'"
report.tls.aggregate.from-address = "'noreply-tls@{{ brand.domain }}'"
report.tls.aggregate.org-name = "'{{ brand.desc }}'"
report.tls.aggregate.contact-info = "'noreply-tls@{{ brand.domain }}'"
report.tls.aggregate.send = "daily"
report.tls.aggregate.max-size = 26214400 # 25 mb
report.tls.aggregate.sign = "['rsa']"
report.submitter = "'mail.{{ brand.domain }}'"

#:::::::::::::::::::::::::#
#::Logging::and::Tracing::#
#:::::::::::::::::::::::::#

# Files
tracer.log.enable = true
tracer.log.type = "log"
tracer.log.ansi = false
tracer.log.level = "info"
tracer.log.path = "/logs"
tracer.log.prefix = "stalwart.log"
tracer.log.rotate = "daily"

# Console
tracer.console.enable = true
tracer.console.type = "console"
tracer.console.level = "trace"
tracer.console.ansi = true
