- name: "Base Install | AppArmor | Install"
  community.general.xbps:
    name: apparmor
    state: present

- name: "Base Install | AppArmor | Set enforce"
  lineinfile:
    path: /etc/default/apparmor
    regexp: '^APPARMOR='
    line: 'APPARMOR=enforce'
    create: false

- name: "Base Install | AppArmor | Check kernel parameters"
  lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*apparmor=1 security=apparmor'
    state: absent
  check_mode: true
  register: grub_cmdline_check
  changed_when: false

- name: "Base Install | AppArmor | Set kernel parameters"
  lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)\"$"
    line: '\1 apparmor=1 security=apparmor"'
  when: grub_cmdline_check.found == 0
