- name: "Base Install | Bluetooth | Install packages"
  become: true
  shell: "xbps-install -y bluez"

- name: "Base Install | Bluetooth | Check if bluetoothd is enabled"
  stat:
    path: "/var/service/bluetoothd"
  register: btd_stat

- name: "Base Install | Bluetooth | Enable service"
  become: true
  shell: "ln -s /etc/sv/bluetoothd /var/service"
  when: not btd_stat.stat.exists

- name: "Base Install | Bluetooth | Add user to group"
  become: true
  shell: "usermod -aG bluetooth {{ ansible_user }}"
