- name: "Base Install | Cups | Install"
  become: true
  shell: "xbps-install -Sy {{ printer_driver }}"
  loop:
    - cups
    - cups-filters
    - gutenprint
    - hplip
    - foomatic-db
    - foomatic-db-nonfree
    - brother-brlaser
    - epson-inkjet-printer-escpr
    - cnijfilter2
  loop_control:
    loop_var: printer_driver

- name: "Base Install | Cups | Check if service is enabled"
  stat:
    path: "/var/service/cupsd"
  register: cupsd_stat

- name: "Base Install | Cups | Enable service"
  become: true
  shell: "ln -s /etc/sv/cupsd /var/service"
  when: not cupsd_stat.stat.exists
