#TODO: fix os suspending
#- name: "Base Install | Gnome | Install packages"
#  become: true
#  shell: "xbps-install -Sy gnome-core gdm adwaita-fonts xorg xtools xdg-desktop-portal-gnome xdg-utils xdg-user-dirs gnome-terminal"
#
#- name: "Base Install | Gnome | Restart host"
#  reboot:
#    reboot_timeout: 600
#
#- name: "Base Install | Gnome | Check if gdm is enabled"
#  stat:
#    path: "/var/service/gdm"
#  register: gdm_stat
#
#- name: "Base Install | Gnome | Check if NetworkManager is enabled"
#  stat:
#    path: "/var/service/NetworkManager"
#  register: nmgr_stat
#
#- name: "Base Install | Gnome | Check if dbus is enabled"
#  stat:
#    path: "/var/service/dbus"
#  register: dbus_stat
#
#- name: "Base Install | Gnome | Enable gdm service"
#  become: true
#  shell: "ln -s /etc/sv/gdm /var/service"
#  when: not gdm_stat.stat.exists
#
#- name: "Base Install | Gnome | Enable dbus service"
#  become: true
#  shell: "ln -s /etc/sv/dbus /var/service"
#  when: not dbus_stat.stat.exists
#
#- name: "Base Install | Gnome | Enable NetworkManager service"
#  become: true
#  shell: "ln -s /etc/sv/NetworkManager /var/service"
#  when: not nmgr_stat.stat.exists
