- name: "Base Install | Drivers | Nvidia | Install"
  community.general.xbps:
    state: present
    update_cache: true
    name: "{{ nvidia_packages }}"
  vars:
    nvidia_packages:
      - "nvidia"
      - "nvidia-libs-32bit"
      - "mesa-dri"
  when: nvidia.driver.install

- name: "Base Install | Drivers | Nvidia | Install 32-bit compatibility libraries"
  community.general.xbps:
    state: present
    name: "{{ library }}"
  loop:
    - "libgcc-32bit"
    - "libstdc++-32bit"
    - "libdrm-32bit"
    - "libglvnd-32bit"
    - "mesa-dri-32bit"
  loop_control:
    loop_var: library

- name: "Base Install | Drivers | Nvidia | Check kernel parameters"
  lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*nvidia-drm.modeset=1'
    state: absent
  check_mode: true
  register: grub_cmdline_check
  changed_when: false

- name: "Base Install | Drivers | Nvidia | Set kernel parameters"
  lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)\"$"
    line: '\1 nvidia-drm.modeset=1"'
  when: grub_cmdline_check.found == 0
  register: grub_cmdline_set

- name: "Base Install | Drivers | Nvidia | Update-grub"
  command: update-grub
  when: grub_cmdline_set is defined and grub_cmdline_set.changed
