- name: "Base Install | Plymouth | Check kernel parameters"
  lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash rd.plymouth=1.*'
    state: absent
  check_mode: true
  register: grub_cmdline_check
  changed_when: false

- name: "Base Install | Plymouth | Set kernel parameters"
  lineinfile:
    path: /etc/default/grub
    backrefs: true
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=")(.*?)"$'
    line: '\1quiet splash rd.plymouth=1 \2"'
    backup: true
  when: grub_cmdline_check.found == 0
  register: grub_cmdline_set

- name: "Base Install | Plymouth | Set theme and refresh dracut"
  command: plymouth-set-default-theme -R spinner

- name: "Base Install | Plymouth | Update-grub"
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub_cmdline_set is defined and grub_cmdline_set.changed
