services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    restart: {{ docker.restart_policy }}
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - "{{ docker.data_dir }}/wg-easy:/etc/wireguard"
      - "/lib/modules:/lib/modules:ro"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    environment:
      - TZ={{ server.os.timezone }}
      - PORT=51821
      - WG_HOST={{ vps0_public_ipv4 }}
      - INSECURE=true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:51821"]
      interval: "{{ docker.healthcheck.interval }}"
      timeout: "{{ docker.healthcheck.timeout }}"
      retries: "{{ docker.healthcheck.retries }}"
      start_period: "{{ docker.healthcheck.start_period }}"

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64